default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: dpg-d4fihhq4d50c73a380bg-a.oregon-postgres.render.com
  port: 5432
  username: krishna_goshala_user
  password: dUiyMlTdL4rtOPtr8UZmamiMeiUWffs6

development:
  <<: *default
  database: krishna_goshala

test:
  <<: *default
  database: krishna_goshala_test

production:
  primary:
    <<: *default
    database: krishna_goshala

  cable:
    <<: *default
    database: krishna_goshala

  queue:
    <<: *default
    database: krishna_goshala

  cache:
    <<: *default
    database: krishna_goshala
